kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeploy
spec:
   replicas: 1
   selector:     
    matchLabels:
     name: deploy
   template:
     metadata:
       labels:
         name: deploy
     spec:
      containers:
        - name: mycon1
          image: httpd
          ports:
           - containerPort: 8080
