kind: Deployment
apiVersion: apps/v1
metadata:
   name: my-newdeploy
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: my-app
   template:
     metadata:
       labels:
         app: my-app
     spec:
      containers:
        - name: webcon
          image: httpd
          ports:
            - containerPort: 80

