kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: deployment
   template:
     metadata:
       labels:
         name: deployment
     spec:
      containers:
        - name: webcon
          image: httpd
          ports:
            - containerPort: 80

