apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: dev-team
spec:
  limits:
  - type: Container
    max:
      cpu: "1"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    default:                      #Sets the default resource limit if none is specified in the Pod spec
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:              #Sets the default resource request if none is specified in the Pod spec
      cpu: "200m"
      memory: "256Mi"
