#Note that resourceqouta scope is name-space. so these are limits for entire name-space. 
#For containers inside pod, limits are define in ymal manifest i.e pod ,deploy etc
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: dev-team
spec:
  hard:
    pods: "4"
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "3Gi"
    
