#Create secret using CLI
#kubectl create secret generic dbsecret --from-literal=username=admin --from-literal=password=asdfghj
#use the secret as keyRefrence , in this case i am using key value of "username" from "dbsecret" for env "USERNAME"

apiVersion: v1
kind: Pod
metadata:
  name: pod1-secret
spec:
  containers:
  - name: container1
    image: nginx
    env:
    - name: USERNAME  #is the name of variable
      valueFrom:
        secretKeyRef:
          name: dbsecret   # dbsecret is the secret name created using CLI
          key: username    #username is the key that is called from dbsecret, "username=admin" the value admin will be used for env "USERNAME"
