#In this example , secret created for docker registery is used as "env"
#create secret using : kubectl create secret docker-registry my-registry-secret  --docker-server=https://index.docker.io/v1/  --docker-username=admin  --docker-password=xyz123 --docker-email=your-email@example.com
#Docker registry  secrets are  used for pulling private container images.


apiVersion: v1
kind: Pod
metadata:
  name: pod2-secret
spec:
  containers:
  - name: container1
    image: nginx
    envFrom:
    - secretRef:
       name: my-registry-secret
