apiVersion: v1
kind: Pod
metadata:
  name: web-static
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: web-content
      mountPath: /usr/share/nginx/html
  volumes:
  - name: web-content
    persistentVolumeClaim:
      claimName: static-nfs-pvc
