#apply manifes--> kubectl apply -f sidecar.yml
# port-forward --> kubectl port-forward pod/sidecar-example 8080:80
# Curl the web-page--> curl http://localhost:8080

apiVersion: v1
kind: Pod
metadata:
  name: sidecar-example
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo Hello from app > /usr/share/nginx/html/index.html && sleep 3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: shared-data
    emptyDir: {}
