apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveliness-probe
spec:
  containers:
  - name: liveness-container
    image: ubuntu
    args:
    - /bin/sh
    - -c
    - touch /tmp/health-check; sleep 1000
    livenessProbe:                                          
      exec:
        command:                                         
        - cat                
        - /tmp/health-check
      initialDelaySeconds: 5       #Wait time before starting probes.     
      periodSeconds: 5             #Frequency of checks.
      timeoutSeconds: 30           #The number of seconds after which the probe times out if no response is received.
                                   #If the container doesn't respond within this time, the probe is considered failed.
