kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 2
   selector:     
    matchLabels:
      app: apache
      ver: blue
   template:
     metadata:
       labels:
         app: apache
         ver: blue
     spec:
      containers:
        - name: webcon
          image: apache
