#deletes old pods before creating new pods.
#Causes down-Time
#simple and fast for none-production and testing
# To test change image of container--> kubectl set image deploy/mydeployments webcon=nginx:1.23 --record
kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydeployments
spec:
   replicas: 2
   strategy:
     type: Recreate
   selector:     
    matchLabels:
      app: nginx-app
   template:
     metadata:
       name: testpod
       labels:
         app: nginx-app
     spec:
      containers:
        - name: webcon
          image: nginx:1.21
          ports:
           - containerPort: 80
