kind: Pod
apiVersion: v1
metadata:
  name: mypod1
  labels:                                                   
    env: development
    class: pods
spec:
    containers:
      - name: cont1
        image: ubuntu
        command: ["/bin/bash", "-c", "while true; do echo Hello-World; sleep 5 ; done"]

