kind: Pod
apiVersion: v1
metadata:
  name: nodelabels
  labels:
    env: development
spec:
  containers:
    - name: cont2
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-World; sleep 5 ; done"]
  nodeSelector:                                         
    env: development
