
#instrctions: apply manifest using kubectl apply -f pod2.yml
#describe pod to check service accounte : kubectl describe pod mginx-pod | grep -i serviceaccount
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
spec:
  serviceAccountName: pod-reader
  containers:
  - name: nginx
    image: nginx:1.25.3
    ports:
    - containerPort: 80
