apiVersion: v1
kind: Pod
metadata:
  name: sa-test-pod
  namespace: default
spec:
  serviceAccountName: pod-reader
  containers:
  - name: curl
    image: curlimages/curl:8.4.0
    command: ["sleep", "3600"]
