apiVersion: v1
kind: Pod
metadata:
  name: hostpath-volume
spec:
  containers:
  - image: ubuntu
    name: testc
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
    - mountPath: /tmp/hostpath  #inside container
      name: testvolume
  volumes:
  - name: testvolume
    hostPath:
      path: /tmp/data #on host machine
      type: DirectoryOrCreate
