apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        envFrom:
        - secretRef:
            name: postgres-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:                   #This is define so that each pod has its own storage , if not define , all pod will use same storage
  - metadata:
      name: postgres-storage   
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi                     #K8s will create pv (volumename-statefuleset-name) -then pvc to claim this storage if there is default storage class exist or if 
                                           #matching PV (volumename-statefuleset-name)is craeted manually or already exsist.
                                           #if no default storage class is available or PV not exsist , PVC will remain pending
