apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: bXlkYg==         # base64 for "mydb"   echo -n "mydb" | base64
  POSTGRES_USER: YWRtaW4=       # base64 for "admin"  echo -n "admin" | base64
  POSTGRES_PASSWORD: c2VjcmV0   # base64 for "secret"  echo -n "secret" | base64
