apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer   #name of conatiner which will run inside pod
    image: nginx        #container image
    ports:
    - containerPort: 80   
