#Use only key from configMap not entire configMap
#configMap created using --> kubectl create configmap conf-2 --from-literal=user_name=admin --from-literal=user_group=testing
#in this example from "conf-2" we are using value of  key "user_name" for env "USER_NAME". although there are two key value pairs in cinfigmap.
#kubectl exec -it  pod --printenv   --> to print environmental vars.
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: demo-container
    image: nginx
    env:
    - name: USER_NAME
      valueFrom:   
        configMapKeyRef:   
          name: conf-2
          key: user_name
